### ISSUE TITLE
Parse condition with comparison_operator and binary_operator wrong

### ISSUE THREAD

**Issue by thanglongnamnay** [PrestonKnopp/tree-sitter-gdscript#21]
Parse this
```
1 == 2 or 3 == 4
```
Output:
```lisp
(expression_statement
  (comparison_operator
    (integer)
    (binary_operator
      (integer)
      (integer))
    (integer)))
```
Expected output:
```lisp
(expression_statement
  (binary_operator
    (comparison_operator
      (integer)
      (integer))
    (comparison_operator
      (integer)
      (integer))))
```

**Comment by PrestonKnopp** [comment]
Wow, I wonder how long precedence has been wrong. I wish I wrote tests for that.

Thanks for finding this issue. I'll find some time to look into this in the next couple of days.

**Comment by PrestonKnopp** [comment]
Hi, I believe it should be fixed now. If you have a moment could you verify that it works for you?

Thanks again.

**Comment by thanglongnamnay** [comment]
Yes, this fixes my case. I think we can close this issue now.
