### ISSUE TITLE
Support for gdscript 2

### ISSUE THREAD

**Issue by Cretezy** [PrestonKnopp/tree-sitter-gdscript#9]
Godot 4 comes with gdscript 2. I've experience some ERROR nodes with the current version.

Specifically:
- [Annotations](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#annotations) (`@export` and co., `@onready`, `@tool`, `@rpc`, etc) are new in Godot 4 and are not recognized
- [Getters/setters](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#properties-setters-and-getters) have a new syntax in Godot 4 and are not recognized
- Anonymous functions (tracked in https://github.com/PrestonKnopp/tree-sitter-gdscript/issues/11)
- ~~[Scene unique nodes](https://docs.godotengine.org/en/latest/tutorials/scripting/scene_unique_nodes.html) (`%Node`) were introduced in Godot 3.5 and are not recognized~~ fixed in https://github.com/PrestonKnopp/tree-sitter-gdscript/pull/10
- ~~[Signals](https://docs.godotengine.org/en/latest/classes/class_signal.html) now support types in Godot 4 and are not recognized~~ fixed in https://github.com/PrestonKnopp/tree-sitter-gdscript/pull/10

It's possible there's more, these are just the ones I've found.

![image](https://user-images.githubusercontent.com/2672503/207432398-e4e928d6-274b-4ca8-9071-84679bfd810c.png)
![image](https://user-images.githubusercontent.com/2672503/207432879-4eed66fd-b8de-46ba-9e9e-0c68275bb673.png)
![image](https://user-images.githubusercontent.com/2672503/207433462-861b0177-1e93-4386-b3e4-90f7feed8175.png)

**Comment by Cretezy** [comment]
Opened a PR for most of this support: https://github.com/PrestonKnopp/tree-sitter-gdscript/pull/10

Missing in PR:
- `@rpc`
- Setters/getters

**Comment by Cretezy** [comment]
@PrestonKnopp Maybe we can keep this open as it's not fully resolved, unless you planned on making separate issues for annotations and setters/getters.

**Comment by PrestonKnopp** [comment]
I'm making separate issuse

**Comment by PrestonKnopp** [comment]
Annotations from what I can tell have the following grammar: 

```
argument_list: "(" (expression ("," expression)* )? ")"
annotation: "@" identifier argument_list?
```

**Comment by A-Lamia** [comment]
Is there being no support for GD2 causing highlights to not work ?

**Comment by PrestonKnopp** [comment]
Yes that is correct. The only support for GD2 is from Cretezys PR (#10). I'll have to set aside some time to work on this this weekend.

**Comment by PrestonKnopp** [comment]
- Added annotation rules in: acb80d1
- Added setget v2 rules in: 008ea91

Tests are passing, but haven't tested it in an editor yet.

**Comment by A-Lamia** [comment]
Highlighting is incorrect when just setting `get`

![image](https://user-images.githubusercontent.com/6450181/217888926-0550f786-2361-4abd-8dae-806cfa209664.png)

**Comment by PrestonKnopp** [comment]
@A-Lamia, Thanks! Should now be fixed in 02a8990.

**Comment by A-Lamia** [comment]
Seems to be a highlight issue on the `var` when a variable is declared right after a lambda:
![image](https://user-images.githubusercontent.com/6450181/219958392-c06b37af-8397-4b8f-b82c-914bfcf451a4.png)

**Comment by PrestonKnopp** [comment]
Okay, lambda parsing appears reliable enough for general use. There's many edge cases so issue reports are very welcome.
Main commits for lambda: 1bf83db, 49b138c, dcd1eb0, and a254369.

Also added some other GDScript 2 things such as:
- StringNames 6401ca2
- new NodePath syntax 288280a
- await expressions 2c62c5f

**Comment by PrestonKnopp** [comment]
Closing, AFAICT, tree-sitter-gdscript as of v1.9.0 is synced with the latest godot gdscript commit noted in the readme.

New issues are welcomed.
